# Generated by Django 3.1.6 on 2021-07-11 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('firstname', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('lastname', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('address', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('phone', models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('email', models.EmailField(max_length=200, null=True, validators=[django.core.validators.EmailValidator()])),
                ('occupation', models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('profile_pic', models.FileField(default='static/images/8.png', upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
