# Generated by Django 3.1.6 on 2021-07-11 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210712_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
