# Generated by Django 3.1.6 on 2021-07-12 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210712_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebooklink',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='FacebookLink'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, default=None, verbose_name='BirthDate(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/images/8.png', upload_to='static/uploads', verbose_name='ProfilePic'),
        ),
    ]
