# Generated by Django 3.1.6 on 2021-07-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210712_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
