# Generated by Django 3.1.6 on 2021-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/images/8.png', max_length=500, upload_to='static/uploads', verbose_name='ProfilePic'),
        ),
    ]
