# Generated by Django 3.1.6 on 2021-07-12 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210712_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='BirthDate(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Update Your Name', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='FirstName'),
        ),
    ]
