# Generated by Django 3.1.6 on 2021-07-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210712_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/images/8.png', max_length=500, upload_to='static/uploads', verbose_name='ProfilePic'),
        ),
    ]
