# Generated by Django 3.1.6 on 2021-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210714_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sendNotification',
            field=models.BooleanField(default=True, verbose_name='Send Login Notification'),
        ),
    ]
