# Generated by Django 3.1.6 on 2021-07-25 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210721_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, default='Not Updated', null=True, verbose_name='BirthDate(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Name not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
