# Generated by Django 3.1.6 on 2021-07-25 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210725_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebooklink',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='FacebookLink'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='PhoneNumber'),
        ),
    ]
