# Generated by Django 3.1.6 on 2021-08-19 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210801_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebooklink',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Name not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='Phone Number'),
        ),
    ]
