# Generated by Django 3.1.6 on 2021-07-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
