# Generated by Django 3.1.6 on 2021-07-21 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0004_auto_20210721_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
