# Generated by Django 3.1.6 on 2021-07-26 21:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0008_auto_20210721_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='Not Updated', null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Put Your Content Here'),
        ),
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_pic',
            field=models.ImageField(default='static/images/8.png', max_length=500, upload_to='static/uploads', verbose_name='News Pic'),
        ),
    ]
