# Generated by Django 3.1.6 on 2021-07-30 02:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0013_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='as', max_length=49),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default='as', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Tags',
            field=models.CharField(choices=[('1', 'Education'), ('2', 'Sports'), ('3', 'Important'), ('4', 'Four'), ('5', 'Five')], default='Not Updated', max_length=200, null=True, verbose_name='Tags'),
        ),
    ]
