# Generated by Django 3.1.6 on 2021-07-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0014_auto_20210730_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='news',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='news',
            name='my_field2',
        ),
    ]
