# Generated by Django 3.1.6 on 2021-07-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0015_auto_20210730_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Tags',
            field=models.CharField(choices=[('1', 'Education'), ('2', 'Sports'), ('3', 'Important'), ('4', 'Dailynews'), ('5', 'Routine')], default='Not Updated', max_length=200, null=True, verbose_name='Category'),
        ),
    ]
