# Generated by Django 3.1.6 on 2021-07-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0016_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Tags',
            field=models.CharField(choices=[('Education', 'Education'), ('Sports', 'Sports'), ('Important', 'Important'), ('Dailynews', 'Dailynews'), ('Routine', 'Routine')], default='Not Updated', max_length=200, null=True, verbose_name='Category'),
        ),
    ]
