# Generated by Django 3.1.6 on 2021-08-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0019_course_courseenrollement_coursemodule_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollement',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.course'),
        ),
    ]
