# Generated by Django 3.1.6 on 2021-08-13 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0021_coursemodule_modulelecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_summary',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='to_learn',
            field=models.CharField(default='You can join this course right away', max_length=200, null=True, verbose_name='What students needs to learn before joining this course'),
        ),
    ]
