# Generated by Django 3.1.6 on 2021-08-13 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0023_auto_20210813_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ('modulenumber',)},
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='modulenumber',
            field=models.IntegerField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Lecture Number'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Module Name'),
        ),
    ]
