# Generated by Django 3.1.6 on 2021-08-13 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0024_auto_20210813_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='to_learn',
            field=ckeditor.fields.RichTextField(default='You can join this course right away', max_length=200, null=True, verbose_name='What students needs to learn before joining this course'),
        ),
    ]
