# Generated by Django 3.1.6 on 2021-08-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0027_auto_20210813_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ('-modulenumber',)},
        ),
    ]
