# Generated by Django 3.1.6 on 2021-08-14 08:36

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0029_auto_20210813_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_summary',
            field=models.CharField(default='Not Updated', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Course Summary'),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_learn',
            field=ckeditor.fields.RichTextField(default='You can join this course right away', max_length=50000, null=True, verbose_name='What students needs to learn before joining this course'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='ModuleLecture',
            field=ckeditor.fields.RichTextField(max_length=50000, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Module Lecture'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='modulenumber',
            field=models.IntegerField(null=True, verbose_name='Lecture Number'),
        ),
    ]
