# Generated by Django 3.1.6 on 2021-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0036_auto_20210815_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Not Updated', max_length=200, null=True, verbose_name='Course Name'),
        ),
    ]
