# Generated by Django 3.1.6 on 2021-08-16 01:28

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnToEarn', '0037_auto_20210815_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='ModuleLecture',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=50000, null=True, verbose_name='Module Lecture'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Not Updated', null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Put Your Content Here'),
        ),
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('like', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
