# Generated by Django 3.1.6 on 2021-08-16 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0038_auto_20210816_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Module Name'),
        ),
    ]
