# Generated by Django 3.1.6 on 2021-08-16 23:37

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0039_auto_20210817_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='ModuleLecture',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=50000, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Module Lecture'),
        ),
    ]
