# Generated by Django 3.1.6 on 2021-08-16 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0040_auto_20210817_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='ModuleLecture',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=50000, null=True, verbose_name='Module Lecture'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.CharField(max_length=200, null=True, verbose_name='Module Name'),
        ),
    ]
