# Generated by Django 3.1.6 on 2021-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0042_auto_20210817_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Star'), (2, '2-Star'), (3, '3-Star'), (4, '4-Star'), (5, '5-Star')], verbose_name='Choose Your Rating'),
        ),
    ]
