# Generated by Django 3.1.6 on 2021-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0043_auto_20210817_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='comment',
            field=models.CharField(default='Not Updated', max_length=50000, null=True),
        ),
    ]
