# Generated by Django 3.1.6 on 2021-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0044_auto_20210817_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
