# Generated by Django 3.1.6 on 2021-08-21 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnToEarn', '0045_coursereview_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.PositiveSmallIntegerField(default=0, verbose_name='Number')),
                ('question', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('option1', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('option2', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('option3', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('option4', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('answer', models.CharField(default='Not Updated', max_length=5000, null=True)),
                ('exammodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.exammodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
