# Generated by Django 3.1.6 on 2021-08-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0046_exammodel_examqna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examqna',
            name='user',
        ),
    ]
