# Generated by Django 3.1.6 on 2021-08-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0049_exammodel_examnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempted',
            name='course',
        ),
        migrations.AddField(
            model_name='attempted',
            name='exammodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.exammodel'),
        ),
    ]
