# Generated by Django 3.1.6 on 2021-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0053_auto_20210821_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examqna',
            name='answer',
            field=models.CharField(max_length=5000, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='examqna',
            name='option1',
            field=models.CharField(max_length=5000, null=True, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='examqna',
            name='option2',
            field=models.CharField(max_length=5000, null=True, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='examqna',
            name='option3',
            field=models.CharField(max_length=5000, null=True, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='examqna',
            name='option4',
            field=models.CharField(max_length=5000, null=True, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='examqna',
            name='question',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
