# Generated by Django 3.1.6 on 2021-08-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0055_auto_20210821_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examqna',
            name='user',
        ),
    ]
