# Generated by Django 3.1.6 on 2021-08-24 21:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0062_auto_20210824_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True)),
                ('exammodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.exammodel')),
            ],
        ),
    ]
