# Generated by Django 3.1.6 on 2021-08-24 21:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnToEarn', '0063_examanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='question',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='exammodel',
        ),
        migrations.AddField(
            model_name='examanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True)),
                ('exammodel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.exammodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examanswer',
            name='examquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnToEarn.examquestion'),
        ),
    ]
