# Generated by Django 3.1.6 on 2021-08-24 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnToEarn', '0065_auto_20210825_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
