# Generated by Django 3.1.6 on 2021-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0066_auto_20210825_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='time',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
