# Generated by Django 3.1.6 on 2021-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0067_examanswer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
