# Generated by Django 3.1.6 on 2021-08-24 23:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0068_examanswer_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Paste Your PDF HERE', max_length=5000, null=True),
        ),
    ]
