# Generated by Django 3.1.6 on 2021-08-25 00:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0069_auto_20210825_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Paste Your Question in PDF Format HERE', max_length=5000, null=True),
        ),
    ]
