# Generated by Django 3.1.6 on 2021-08-25 00:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0070_auto_20210825_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Paste Your Answer in PDF format here', max_length=5000, null=True),
        ),
    ]
