# Generated by Django 3.1.6 on 2021-08-25 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LearnToEarn', '0071_auto_20210825_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
